# Makefile with two target one is generating application and other is clean removing the object file
$(CC) = gcc

appln:
	$(CC) main.c calc_mean.c calc_sub.c -o appln1

clean:
	rm -f *.o appln
# rm -f *.c comment
